[project]
name = "projetlong"
version = "0.1.0"
description = "RoadEye Guardian: Perception coopérative et IA embarquée"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.4.2",
    "ultralytics>=8.4.0",
    "opencv-python>=4.10.0",
]